<div class='example'>
<span id="spinner" class="glyphicon glyphicon-refresh"></span>
<a href="#" class='record_count'>Total <span class="badge"></span></a>
<span id="found" class="label label-info"></span>
<table id="stream_table" class='table table-striped table-bordered' style="display:none;">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Email</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
        </table>
        <div id="summary"></div>
</div>